#!/usr/bin/env bash
set -euo pipefail

# Push merged local env config to the VPS.
# Public config is tracked in deploy/public.env.<env>.
# Secrets stay local in deploy/.env.<env> (gitignored).
#
# Usage: ./scripts/push-env.sh <staging|production> [user@host]
#
# Examples:
#   ./scripts/push-env.sh staging
#   ./scripts/push-env.sh staging deploy@198.51.100.1
#   ./scripts/push-env.sh production deploy@my-vps.example.com

ENV="${1:?Usage: push-env.sh <staging|production> [user@host]}"
VPS="${2:-deploy@${VPS_HOST:?Set VPS_HOST env var or pass user@host as second arg}}"

if [[ "$ENV" != "production" && "$ENV" != "staging" ]]; then
  echo "Error: environment must be 'staging' or 'production'" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOCAL_PUBLIC_ENV="${SCRIPT_DIR}/../deploy/public.env.${ENV}"
LOCAL_SECRET_ENV="${SCRIPT_DIR}/../deploy/.env.${ENV}"
REMOTE_DIR="/opt/collective-will/${ENV}"
REMOTE_PATH="${REMOTE_DIR}/.env"
TMP_MERGED_ENV="$(mktemp)"

cleanup() {
  rm -f "$TMP_MERGED_ENV"
}
trap cleanup EXIT

if [[ ! -f "$LOCAL_PUBLIC_ENV" ]]; then
  echo "Error: ${LOCAL_PUBLIC_ENV} not found" >&2
  exit 1
fi

if [[ ! -f "$LOCAL_SECRET_ENV" ]]; then
  echo "Error: ${LOCAL_SECRET_ENV} not found" >&2
  exit 1
fi

{
  echo "# Autogenerated by scripts/push-env.sh (${ENV})"
  echo "# Source: deploy/public.env.${ENV} + deploy/.env.${ENV}"
  echo
  cat "$LOCAL_PUBLIC_ENV"
  echo
  cat "$LOCAL_SECRET_ENV"
} > "$TMP_MERGED_ENV"

echo "==> Pushing merged env (${LOCAL_PUBLIC_ENV} + ${LOCAL_SECRET_ENV}) → ${VPS}:${REMOTE_PATH}"

ssh "$VPS" "mkdir -p ${REMOTE_DIR}"
scp "$TMP_MERGED_ENV" "${VPS}:${REMOTE_PATH}"
ssh "$VPS" "chmod 600 ${REMOTE_PATH}"

echo "==> Done. Verifying..."
ssh "$VPS" "wc -l ${REMOTE_PATH} && echo 'Permissions:' && ls -la ${REMOTE_PATH}"
